import { Permission } from '../models/permission';
import { Project } from '../models/project';
import { Status } from '../models/status';
import { User } from '../models/user';

export class DummyData {
  static user: User = {
    Login: 'jtestowy',
    Password: 'jtestowy1',
    FirstName: 'Jan',
    LastName: 'Testowy',
    Permission: Permission.Developer,
  };

  static projects: Project[] = [
    {
      Name: 'Zaliczenie przedmiotu "Programowanie aplikacji webowych"',
      Description: 'Zaliczenie laboratiorów poprzez utworzenie projektu.',
      AddDate: new Date('2023-03-04T16:21:00.000Z'),
      OwnerId: 1,
      Functionalities: [
        {
          Name: 'Przygotwanie planu',
          Description: 'Bez planu ani rusz',
          Priority: 10,
          Status: Status.Done,
          AddDate: new Date('2023-03-04T16:21:00.000Z'),
          OwnerId: 1,
          Tasks: [
            {
              Name: 'Sprawdzenie wymagań na 3',
              Description: 'Wymagania na 3 najważniejsze',
              Priority: 10,
              Status: Status.Done,
              AddDate: new Date('2023-03-04T16:22:00.000Z'),
              StartDate: null,
              EndDate: null,
              ExpectedDate: new Date('2023-07-07T11:15:00.000Z'),
              OwnerId: 1,
              DaysLeft: 0,
            },
            {
              Name: 'Rozpisanie modeli',
              Description: '',
              Priority: 9,
              Status: Status.Done,
              AddDate: new Date('2023-03-04T16:23:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-07T11:18:00.000Z'),
              DaysLeft: 0,
              OwnerId: 1,
            },
            {
              Name: 'Przygotwanie logiki',
              Description: '',
              Priority: 8,
              Status: Status.Done,
              AddDate: new Date('2023-03-04T16:24:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-07T11:28:00.000Z'),
              DaysLeft: 0,
              OwnerId: 1,
            },
            {
              Name: 'Sporządzenie notatek',
              Description: '',
              Priority: 7,
              Status: Status.Done,
              AddDate: new Date('2023-03-04T16:26:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-07T12:30:00.000Z'),
              DaysLeft: 0,
              OwnerId: 1,
            },
          ],
        },
        {
          Name: 'Przygotowanie środowiska do pracy',
          Description: 'Trzeba przygotować komputer do projektu',
          Priority: 10,
          AddDate: new Date('2023-03-04T16:28:00.000Z'),
          Status: Status.Done,
          OwnerId: 1,
          Tasks: [
            {
              Name: 'Zainstalowanie Node.JS',
              Description: '',
              Priority: 10,
              AddDate: new Date('2023-03-04T16:33:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-07T13:00:00.000Z'),
              Status: Status.Done,
              OwnerId: 1,
              DaysLeft: 0,
            },
            {
              Name: 'Zainstalowanie agnulara',
              Description: '',
              Priority: 10,
              Status: Status.Done,
              AddDate: new Date('2023-03-04T16:37:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-07T13:15:00.000Z'),
              OwnerId: 1,
              DaysLeft: 0,
            },
            {
              Name: 'Zainstalowanie gita',
              Description: 'Kontrola wersji może sie przydać',
              Priority: 2,
              Status: Status.Done,
              AddDate: new Date('2023-03-04T16:46:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-15T13:25:00.000Z'),
              OwnerId: 1,
              DaysLeft: 0,
            },
          ],
        },
        {
          Name: 'Utworzenie nowego projektu',
          Description: '',
          Priority: 9,
          AddDate: new Date('2023-03-04T16:51:00.000Z'),
          Status: Status.Done,
          OwnerId: 1,
          Tasks: [
            {
              Name: 'Utworzenie nowego projektu na gicie',
              Description: '',
              Priority: 1,
              AddDate: new Date('2023-03-04T16:54:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-07T13:35:00.000Z'),
              Status: Status.Done,
              OwnerId: 1,
              DaysLeft: 0,
            },
            {
              Name: 'Utworzenie nowego projektu w angularze',
              Description: 'ng new $nazwaProjektu',
              Priority: 10,
              Status: Status.Done,
              AddDate: new Date('2023-03-04T16:58:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-07T13:43:00.000Z'),
              OwnerId: 1,
              DaysLeft: 0,
            },
            {
              Name: 'Zainstalowanie gita',
              Description: 'Kontrola wersji może sie przydać',
              Priority: 2,
              Status: Status.Done,
              AddDate: new Date('2023-03-04T17:01:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-07T13:32:00.000Z'),
              OwnerId: 1,
              DaysLeft: 0,
            },
          ],
        },
        {
          Name: 'Pierwszy komponent',
          Description: '',
          Priority: 8,
          AddDate: new Date('2023-03-04T17:05:00.000Z'),
          Status: Status.Done,
          OwnerId: 1,
          Tasks: [
            {
              Name: 'Utworzenie nowego komponentu',
              Description: 'ng g c $nazwaKomponentu --skip-tests=true',
              Priority: 10,
              AddDate: new Date('2023-03-04T17:09:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-07T14:00:00.000Z'),
              Status: Status.Done,
              OwnerId: 1,
              DaysLeft: 0,
            },
            {
              Name: 'Utworzenie widoku w .html',
              Description: '',
              Priority: 10,
              Status: Status.Done,
              AddDate: new Date('2023-03-04T17:13:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-07T15:00:00.000Z'),
              OwnerId: 1,
              DaysLeft: 0,
            },
            {
              Name: 'Przygotowanie logiki komponentu w .ts',
              Description: 'No chyba że jest dumb component',
              Priority: 7,
              Status: Status.Done,
              AddDate: new Date('2023-03-04T17:28:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-07T16:00:00.000Z'),
              OwnerId: 1,
              DaysLeft: 0,
            },
          ],
        },
        {
          Name: 'Skończenie projektu',
          Description: '',
          Priority: 8,
          AddDate: new Date('2023-03-04T17:31:00.000Z'),
          Status: Status.Done,
          OwnerId: 1,
          Tasks: [
            {
              Name: 'Jeden domyslny użytkownik, bez logowania',
              Description: '',
              Priority: 10,
              AddDate: new Date('2023-07-08T13:00:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-15T11:15:00.000Z'),
              Status: Status.Done,
              OwnerId: 1,
              DaysLeft: 0,
            },
            {
              Name: 'Jeden domyślny projekt',
              Description: '',
              Priority: 10,
              Status: Status.Done,
              AddDate: new Date('2023-03-04T17:37:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-09T13:35:00.000Z'),
              OwnerId: 1,
              DaysLeft: 0,
            },
            {
              Name: 'Funkcjonalności projektowe - prosty CRUD + lista',
              Description: 'i powiązania funkcjonalność<->zadanie',
              Priority: 7,
              Status: Status.Done,
              AddDate: new Date('2023-03-04T17:37:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-11T13:50:00.000Z'),
              OwnerId: 1,
              DaysLeft: 0,
            },
            {
              Name: 'Zadania - prosty CRUD + kanban (todo/doing/done)',
              Description: 'i powiązania zadanie<->funkcjonalność',
              Priority: 7,
              Status: Status.Done,
              AddDate: new Date('2023-03-04T17:38:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-13T16:20:00.000Z'),
              OwnerId: 1,
              DaysLeft: 0,
            },
            {
              Name: 'Zmiana statusu funckjonalności w zależności od statusów jego zadań',
              Description: '',
              Priority: 7,
              Status: Status.Done,
              AddDate: new Date('2023-03-04T1:38:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-14T11:00:00.000Z'),
              OwnerId: 1,
              DaysLeft: 0,
            },
          ],
        },
        {
          Name: 'Wprowadzenie dodatkowych funkcjonalności i poprawki',
          Description: '',
          Priority: 3,
          AddDate: new Date('2023-03-04T17:42:00.000Z'),
          Status: Status.Done,
          OwnerId: 1,
          Tasks: [
            {
              Name: 'Dodawanie więcej projetków',
              Description: '',
              Priority: 4,
              AddDate: new Date('2023-03-07T11:40:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-14T13:30:00.000Z'),
              Status: Status.Done,
              OwnerId: 1,
              DaysLeft: 0,
            },
            {
              Name: 'Poprawienie estetyki i wyglądu',
              Description: 'Trzeba się z kimś skonsultować z dobrym gustem',
              Priority: 6,
              Status: Status.Doing,
              AddDate: new Date('2023-03-04T17:51:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-14T16:30:00.000Z'),
              OwnerId: 1,
              DaysLeft: 0,
            },
            {
              Name: 'Poprosić koleżankę o dobranie kolorów',
              Description: '',
              Priority: 2,
              Status: Status.ToDo,
              AddDate: new Date('2023-03-04T17:51:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-14T19:20:00.000Z'),
              OwnerId: 1,
              DaysLeft: 0,
            },
          ],
        },
        {
          Name: 'Prezentacja i ocena',
          Description: '',
          Priority: 10,
          AddDate: new Date('2023-07-06T14:12:00.000Z'),
          Status: Status.Done,
          OwnerId: 1,
          Tasks: [
            {
              Name: 'Sprawdzić czy działa przed prezentacją',
              Description: '',
              Priority: 10,
              AddDate: new Date('2023-07-06T14:14:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-15T11:15:00.000Z'),
              Status: Status.Done,
              OwnerId: 1,
              DaysLeft: 0,
            },
            {
              Name: 'Sprawdzić czy na pewno działa',
              Description: '',
              Priority: 10,
              AddDate: new Date('2023-07-10T18:58:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-15T11:15:00.000Z'),
              Status: Status.Done,
              OwnerId: 1,
              DaysLeft: 0,
            },
            {
              Name: 'Wybłagać 3',
              Description: '',
              Priority: 10,
              Status: Status.Doing,
              AddDate: new Date('2023-07-06T14:14:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-15T11:15:00.000Z'),
              OwnerId: 1,
              DaysLeft: 0,
            },
          ],
        },
      ],
    },
    {
      Name: 'Remont pokoju',
      Description:
        'Trzeba odświeżyć pokój przed wkroczeniem na nową drogę życia - inżyniera',
      AddDate: new Date('2023-07-11T21:43:00.000Z'),
      OwnerId: 1,
      Functionalities: [
        {
          Name: 'Malowanie',
          Description: '',
          Priority: 3,
          AddDate: new Date('2023-07-11T21:44:00.000Z'),
          Status: Status.ToDo,
          OwnerId: 1,
          Tasks: [],
        },
        {
          Name: 'Nowe meble',
          Description: '',
          Priority: 10,
          AddDate: new Date('2023-07-11T21:44:00.000Z'),
          Status: Status.Doing,
          OwnerId: 1,
          Tasks: [
            {
              Name: 'Przespać się przed decyzją',
              Description: '',
              Priority: 10,
              Status: Status.Done,
              AddDate: new Date('2023-07-11T21:44:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-14T16:00:00.000Z'),
              OwnerId: 1,
              DaysLeft: 0,
            },
            {
              Name: 'Wybrać meble do kupna',
              Description: '',
              Priority: 10,
              Status: Status.Done,
              AddDate: new Date('2023-07-11T21:44:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-15T16:00:00.000Z'),
              OwnerId: 1,
              DaysLeft: 0,
            },
            {
              Name: 'Zamówić nowe meble',
              Description: '',
              Priority: 10,
              Status: Status.Doing,
              AddDate: new Date('2023-07-11T21:46:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-15T19:00:00.000Z'),
              OwnerId: 1,
              DaysLeft: 0,
            },
            {
              Name: 'Sprawdzić czy mnie stać na nowe meble',
              Description: '',
              Priority: 10,
              Status: Status.ToDo,
              AddDate: new Date('2023-07-11T21:46:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-14T19:00:00.000Z'),
              OwnerId: 1,
              DaysLeft: 0,
            },
            {
              Name: 'Odebrać nowe meble',
              Description: '',
              Priority: 10,
              Status: Status.ToDo,
              AddDate: new Date('2023-07-11T21:47:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-20T14:00:00.000Z'),
              OwnerId: 1,
              DaysLeft: 0,
            },
            {
              Name: 'Złożyć nowe meble',
              Description: '',
              Priority: 6,
              Status: Status.ToDo,
              AddDate: new Date('2023-07-11T21:49:00.000Z'),
              StartDate: new Date(),
              EndDate: new Date(),
              ExpectedDate: new Date('2023-07-30T19:00:00.000Z'),
              OwnerId: 1,
              DaysLeft: 0,
            },
          ],
        },
      ],
    },
  ];
}
